### ISSUE TITLE
HTML entities not supported by MarkDown

### ISSUE THREAD

**Issue by hostilefork** [rebolek/lest#17]
Essentially this means that certain & in the source text should *not* be escaped as `&amp;` in the HTML.

It's a little tricky and I don't know how CommonMark is going about it.  What if you write `I enjoy Q&A; it's fun`?  That works, but if you write `I enjoy Q&AMP; it's fun` StackOverflow won't escape (when writing questions).  It's as if it has a list of what the valid entities are, and will only keep from escaping if it's one of those.

*(I know there's lots of Markdown stuff, just mentioning things that I use.  e.g. this breaks [`&delta;` and `&rarr;` on the nocycle page](http://nocycle.hostilefork.com/))*

**Comment by rebolek** [comment]
Fixed in Commonmark.reb (it actually brought one regression but I will come to that later). Please note that currently entities are **gt**, **lt**, **amp** and **quot** only. Better list of entities will be implemented later.
